// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://freltzruwiggwigfqagg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZyZWx0enJ1d2lnZ3dpZ2ZxYWdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNjAzMjEsImV4cCI6MjA2MzYzNjMyMX0.Zk9zGAAdh4KskHTza-g5jeHzWaQJHs_IHXlVN9mumic";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);